# Generated by Django 3.2.7 on 2021-09-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=500)),
                ('foreword_by', models.CharField(max_length=500)),
                ('editer1', models.CharField(max_length=500)),
                ('editer2', models.CharField(blank=True, max_length=500)),
                ('publication', models.CharField(max_length=1000)),
                ('release_date', models.DateTimeField()),
                ('best_seller', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='bookimg')),
                ('language', models.CharField(max_length=100)),
                ('isbn_13', models.IntegerField()),
                ('isbn_10', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
