# Generated by Django 3.2.7 on 2021-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ebook',
            field=models.FileField(default=2, upload_to='ebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
