# Generated by Django 3.2.7 on 2021-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mybooks_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
