# Generated by Django 3.2.7 on 2021-10-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211001_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='read_status',
        ),
    ]
