# Generated by Django 3.2.7 on 2021-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_books_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
