# Generated by Django 3.2.7 on 2021-10-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mybooks_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mybooks',
        ),
    ]
