# Generated by Django 3.2.7 on 2021-10-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_my'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
